[package]
name = "oteryn-foundation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[package.metadata.oteryn]
category = "foundation"
release-role = "production"

[dependencies]
tokio.workspace = true

[lints]
workspace = true
